# fly.toml app configuration file generated for cm-admin-demo on 2023-05-09T10:06:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cm-admin-demo"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
